spring.application.name=feriaconecta-backend

server.servlet.context-path=/api/v1

## Configuracion de la DB

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=create-drop

## Consola H2

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

## Logging

logging.level.com.feriaconecta.backend=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG